### ISSUE TITLE
Logout error

### ISSUE THREAD

**Issue by zperee** [MastersProjects/ChatMasters#1]
When you try to logout and press the button it throws an exception but it removes your user from the ArrayList. But the application closes only if you press the logout button a second time

**Comment by Phong6698** [comment]
It iterate too much. That means... when you only have 1 Client it tries to iterate 2 times and throws an exception because there is only one Client in the list.

**Comment by Phong6698** [comment]
FIX THIS:
ChatServer.java:77
for (Iterator<User> iterator = userList.iterator(); i<=userList.size(); i++) {

**Comment by zperee** [comment]
It works thx :+1: :tada:
