### ISSUE TITLE
Logout-Fehler

### ISSUE THREAD

**Issue by zmartl** [MastersProjects/ChatMasters#3]
Wenn man zwei Chats öffnet und keine Nachricht in das Nachrichten-Feld hinzufügt, dann kann man sich ausloggen. Sobald aber einer von den beiden eine Nachricht schreibt, kann sich der Benutzer, welcher sich zu einem späteren Zeitpunkt hinzugefügt hat, nicht mehr ausloggen bzw. kann das Fenster nicht mehr schliessen.

**Comment by Phong6698** [comment]
FLOW:
Turn on the Server -> Turn on Client 1 -> Turn on Client 2 -> Write something in Client 1 -> Logout with Client 2

**Comment by Phong6698** [comment]
Ich weiss ned warum aber bi mir funktionierts wieder... @zmartl-bbc chasch du mal din Flow ufzeichne?

**Comment by zmartl** [comment]
@Phong6698 
FLOW:
Turn on the Server => Turn on Client 1 => Turn on Client 2 => Write something in Client 2 => Logout with Client 1 >> Failed!

**Comment by zperee** [comment]
Bi mir failds au nach em luca sim flow aber es entfernt de user vo de arrayList. Frame gaht eifach nöd weg und es git exceptions. :anguished:

**Comment by zperee** [comment]
mer mues nöd unbedingt öpis schribe es faild immer bim erste client

**Comment by Phong6698** [comment]
gfixed

**Comment by zperee** [comment]
hahah es chan sich immer nur de letscht usloge :laughing:

**Comment by Phong6698** [comment]
chan es bitte öper usprobiere ob es gange isch?

**Comment by Phong6698** [comment]
Problem: Wie elie gseit het es chann immer nur de letzt usloge.. will wenn de glöscht wird blieb es die  for schlaufe

**Comment by zperee** [comment]
:+1:
